theme: jekyll-theme-slate

title: Dmitry Sokolov's repositories on GitHub
description: My personal repositories
social:
  name: Dmitry Sokolov
  links:
    - https://www.linkedin.com/in/dmitry-sokolov-66a40894/
    - https://github.com/DmitrySokolov
    - https://stackoverflow.com/users/edit/2267114

page:
  title: